"""
ConcurShield AI — Shared Data Schemas
All agents read/write these structures via session.state
"""

from typing import TypedDict, List, Optional


class EmployeeProfile(TypedDict):
    """Synthetic employee profile generated by Agent 1."""
    employee_id: str
    name: str
    email: str
    department: str
    grade: str
    region: str
    cost_center: str
    manager: str
    risk_tier: str  # Low, Medium, High


class ExpenseItem(TypedDict):
    """A single expense line item."""
    expense_id: str
    employee_id: str
    category: str  # Flight, Hotel, Meal, Taxi, Per Diem, Mileage, Misc
    subcategory: str
    amount: float
    currency: str
    date: str
    vendor: str
    city: str
    description: str
    receipt_number: str
    is_weekend: bool
    is_anomaly: bool
    anomaly_type: Optional[str]  # duplicate, inflated, out_of_policy, weekend_claim


class ReceiptData(TypedDict):
    """Structured receipt data extracted by Agent 2."""
    expense_id: str
    vendor_name: str
    vendor_category: str  # Restaurant, Hotel, Airline, Transport, Other
    merchant_code: str
    transaction_date: str
    amount: float
    currency: str
    payment_method: str
    city: str
    is_weekend: bool
    confidence_score: float  # 0.0 - 1.0 extraction confidence


class PolicyResult(TypedDict):
    """Policy validation result from Agent 3."""
    expense_id: str
    status: str  # APPROVED, REJECTED
    violations: List[str]
    applicable_limit: float
    actual_amount: float
    policy_region: str
    rule_applied: str


class FraudSignal(TypedDict):
    """Individual fraud signal detected by Agent 4."""
    signal_type: str  # duplicate_claim, velocity_anomaly, vendor_pattern, amount_inflation
    severity: str  # LOW, MEDIUM, HIGH, CRITICAL
    description: str
    affected_expense_ids: List[str]
    confidence: float


class FraudResult(TypedDict):
    """Fraud analysis result from Agent 4."""
    employee_id: str
    risk_score: int  # 0-100
    risk_level: str  # LOW, MEDIUM, HIGH, CRITICAL
    signals: List[FraudSignal]
    recommendation: str


class AuditDecision(TypedDict):
    """Final audit decision from Agent 5."""
    employee_id: str
    report_id: str
    decision: str  # APPROVED, REJECTED
    total_amount: float
    total_items: int
    policy_violations: int
    fraud_risk_score: int
    fraud_signals_count: int
    summary: str
    action_items: List[str]
    processed_at: str
